### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by tommedema** [akidee/osmo#1]
Is this still being maintained or are there alternatives available?

My goal is to maintain an updated version of the planet data in Mongo and perform search queries on it.

Thanks,

Tom

**Comment by archix** [comment]
@tommedema I know this is old as fuck, but what did you use for importing data in Mongo in the end? This is still on official OSM wiki.

Thanks,

Igor

**Comment by tommedema** [comment]
@archix I honestly can't remember, it's been 4 years. I remember giving up on OSM due to lack of community activity

**Comment by archix** [comment]
@tommedema Thanks man. Cheers
